__author__ = 'LOVER'

"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""

1 + 2 + 3 + 5 + 8 + 13 + 21 + 34

lHOperand = 1
rHOperand = 2
fibSum = rHOperand
fibRunningTotal = 0

while fibSum < 4000000:
    if fibSum % 2 == 0:
        fibRunningTotal += fibSum
        print(fibRunningTotal)
    fibSum = lHOperand + rHOperand
    lHOperand = rHOperand
    rHOperand = fibSum