'''
Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
find the sum of the even-valued terms.
'''


a = 1
b = 2

#Kinda cheating, but if fibTotal = b at this point, you get your first even number added to fibTotal.
fibNum = 0
fibTotal = 0

while fibNum < 4000000:
    fibNum = a + b
    a = b
    b= fibNum
    #Also, check for evenness should happen earlier in loop.
    if fibNum % 2 == 0:
        fibTotal += fibNum
        
print(fibTotal)

